name: Scrape XKCD Comic
on:
  schedule:
    - cron: "0 */12 * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  get-xkcd-comic:
    name: Get XKCD Comic and Publish
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.x"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check codes
        run: python main.py
      - name: Update repo with new data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update xkcd comic"
  # deploy:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: github-pages
  #   needs: get-xkcd-comic
  #   permissions:
  #     id-token: write
  #     pages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: "main"
  #     - name: Deploy to GitHub Pages
  #       uses: actions/deploy-pages@v4.0.5
  #       with:
  #
  deploy:
    name: Deploy to GitHub Pages
    needs: get-xkcd-comic
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
