name: Scrape XKCD Comic
on:
  # schedule:
  # - cron: "0 0 */1 * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  get-xkcd-comic:
    name: Get XKCD Comic and Publish
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}

      # Upload generated artifact
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./docs
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.x"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check codes
        run: python main.py
      - name: Update repo with new data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update xkcd comic"
  deploy:
    runs-on: ubuntu-latest
    needs: get-xkcd-comic
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        if: github.ref == 'refs/heads/main'
