name: Scrape XKCD Comic
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: "main"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.x"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python script
        run: python main.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Chore: Update XKCD Comic"
          # file_pattern: "docs/* xkcd.json"
    outputs:
      url: ${{ steps.checkout.outputs.url }}
  publish:
    needs: scrape
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ needs.scrape.outputs.url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "main"
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          destination: docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
