name: Scrape and Deploy XKCD Comic
on:
  schedule:
    - cron: "0 */12 * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Scraping and Committing XKCD Comic
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.XKCD_DEPLOY }}
          path: ./docs
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: "docs"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.x"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check codes
        run: python main.py
      - name: Update repo with new data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update xkcd comic"

  # deploy:
  #   name: Deploy to GitHub Pages
  #   needs: build
  #   environment:
  #     name: github-pages
  #     url: {{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         ref: {{ github.head_ref }}
  #         token: {{ secrets.XKCD_DEPLOY }}
